# -*- coding: utf-8 -*-
"""newprobe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMuHigFNAFrGllp7vpTXz50ZhkNlCDEa
"""

import sys, torch, torch.nn as nn, numpy as np, cv2, os, subprocess, glob, shutil, random
from torch.distributions.normal import Normal
from tqdm import tqdm

# ============================================================
# CELL 1: Setup — clone repo and import exact classes from milestone1
# ============================================================
!git clone https://github.com/thepreetam/le-maia.git /content/le-maia -q 2>/dev/null
# Clean up any potential egg-info that might interfere with package discovery
!rm -rf /content/le-maia/src/*.egg-info
!rm -rf /content/le-maia/*.egg-info
# Use standard pip install to ensure package discoverability
!pip install /content/le-maia -q 2>/dev/null
!pip install opencv-python-headless ultralytics torch torchvision numpy matplotlib tqdm -q 2>/dev/null

# --- Diagnosis: Verify directory structure after cloning --- (Leaving for verification if needed)
print('--- Inspecting /content/le-maia/src ---')
!ls -R /content/le-maia/src
print('--------------------------------------')
# ----------------------------------------------------------

# Removed: sys.path.insert(0, '/content/le-maia/src')
# Removed: print(f"sys.path: {sys.path}") # Added for debugging

# --- Clear cached module if previous import failed ---
if 'lewm_vc' in sys.modules:
    del sys.modules['lewm_vc']
if 'lewm_vc.encoder' in sys.modules:
    del sys.modules['lewm_vc.encoder']
# ---------------------------------------------------

from lewm_vc.encoder import LeWMEncoder

torch.manual_seed(42); np.random.seed(42); random.seed(42)
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
RESOLUTION = 256
QUANT_STEP = 2.0 / 255

# Import the EXACT classes from the repo's milestone1_rd_curve.py
# These match the checkpoint exactly — no redefinitions
class ResidualBlock(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.norm1 = nn.InstanceNorm2d(channels)
        self.conv1 = nn.Conv2d(channels, channels, 3, padding=1)
        self.norm2 = nn.InstanceNorm2d(channels)
        self.conv2 = nn.Conv2d(channels, channels, 3, padding=1)
    def forward(self, x):
        residual = x
        x = torch.nn.functional.gelu(self.norm1(x))
        x = self.conv1(x)
        x = torch.nn.functional.gelu(self.norm2(x))
        x = self.conv2(x)
        return x + residual

class LeWMDecoder(nn.Module):
    def __init__(self, latent_dim=192, hidden_dim=512):
        super().__init__()
        self.proj = nn.Conv2d(latent_dim, hidden_dim, 1)
        self.up1 = nn.ConvTranspose2d(hidden_dim, hidden_dim//2, 4, 2, 1)
        self.res1 = ResidualBlock(hidden_dim//2)
        self.up2 = nn.ConvTranspose2d(hidden_dim//2, hidden_dim//4, 4, 2, 1)
        self.res2 = ResidualBlock(hidden_dim//4)
        self.up3 = nn.ConvTranspose2d(hidden_dim//4, hidden_dim//8, 4, 2, 1)
        self.res3 = ResidualBlock(hidden_dim//8)
        self.up4 = nn.ConvTranspose2d(hidden_dim//8, hidden_dim//16, 4, 2, 1)
        self.res4 = ResidualBlock(hidden_dim//16)
        self.final = nn.Sequential(
            nn.Conv2d(hidden_dim//16, hidden_dim//32, 3, 1, 1),
            nn.InstanceNorm2d(hidden_dim//32),
            nn.GELU(),
            nn.Conv2d(hidden_dim//32, 3, 3, 1, 1),
        )
    def forward(self, latent, target_size=None):
        x = self.proj(latent)
        x = self.up1(x); x = self.res1(x)
        x = self.up2(x); x = self.res2(x)
        x = self.up3(x); x = self.res3(x)
        x = self.up4(x); x = self.res4(x)
        x = torch.sigmoid(self.final(x))
        if target_size:
            x = torch.nn.functional.interpolate(x, size=target_size, mode='bilinear', align_corners=False)
        return x

class AffineNormalization(nn.Module):
    def __init__(self, num_channels):
        super().__init__()
        self.scale = nn.Parameter(torch.ones(1, num_channels, 1, 1))
        self.shift = nn.Parameter(torch.zeros(1, num_channels, 1, 1))
    def forward(self, x):
        return x * self.scale + self.shift

class GMMEntropyModel(nn.Module):
    def __init__(self, latent_dim=192, hyper_channels=256, num_components=2):
        super().__init__()
        self.latent_dim = latent_dim
        self.num_components = num_components
        self.hyperprior = nn.Sequential(
            nn.Conv2d(latent_dim, hyper_channels, 3, padding=1), nn.ReLU(),
            nn.Conv2d(hyper_channels, hyper_channels, 3, padding=1, stride=2), nn.ReLU(),
            nn.Conv2d(hyper_channels, hyper_channels, 3, padding=1), nn.ReLU(),
            nn.ConvTranspose2d(hyper_channels, hyper_channels, 4, stride=2, padding=1), nn.ReLU(),
            nn.Conv2d(hyper_channels, latent_dim * num_components * 3, 3, padding=1),
        )
        self.softplus = nn.Softplus()

    def forward(self, x):
        params = self.hyperprior(x)
        B, C, H, W = params.shape
        channels_per_comp = C // self.num_components
        params = params.view(B, self.num_components, channels_per_comp, H, W)
        mu = params[:, :, :self.latent_dim, :, :]
        log_scale = params[:, :, self.latent_dim:2*self.latent_dim, :, :]
        log_weight = params[:, :, 2*self.latent_dim:3*self.latent_dim, :, :]
        scale = self.softplus(log_scale) + 1e-5
        weight = torch.softmax(log_weight, dim=1)
        return mu, scale, weight

class VideoAutoencoder(nn.Module):
    def __init__(self, latent_dim=192):
        super().__init__()
        self.encoder = LeWMEncoder(latent_dim=latent_dim, semantic_surprise=True)
        self.decoder = LeWMDecoder(latent_dim=latent_dim)
        self.affine = AffineNormalization(latent_dim)
    def encode(self, x):
        return self.affine(self.encoder(x, return_surprise=False))
    def decode(self, latent, target_size):
        return self.decoder(latent, target_size=target_size)

def gmm_likelihood_discrete(y, mu, scale, weight, step, epsilon=1e-12):
    B, C, H, W = y.shape
    num_comp = mu.shape[1]
    y_expanded = y.unsqueeze(1).expand(-1, num_comp, -1, -1, -1)
    normal = Normal(mu, scale)
    cdf_upper = normal.cdf(y_expanded + 0.5 * step)
    cdf_lower = normal.cdf(y_expanded - 0.5 * step)
    pmf = torch.clamp(cdf_upper - cdf_lower, min=epsilon, max=1.0)
    mixture_pmf = (weight * pmf).sum(dim=1)
    return -torch.log(mixture_pmf).mean()

def evaluate_model(ae_path, ent_path, frames):
    """Exact copy of milestone1_rd_curve.py evaluate_model()"""
    autoencoder = VideoAutoencoder().to(DEVICE)
    autoencoder.load_state_dict(torch.load(ae_path, map_location=DEVICE, weights_only=False), strict=False)
    autoencoder.eval()
    entropy_model = GMMEntropyModel().to(DEVICE)
    state = torch.load(ent_path, map_location=DEVICE, weights_only=False)
    for k in list(state.keys()):
        if 'mask' in k: del state[k]
    entropy_model.load_state_dict(state, strict=False)
    entropy_model.eval()
    total_bits, total_mse, total_pix = 0.0, 0.0, 0
    with torch.no_grad():
        for frame in frames:
            x = torch.from_numpy(frame).permute(2,0,1).unsqueeze(0).float().to(DEVICE)
            latent = autoencoder.encode(x)
            x_quant = torch.round(latent / QUANT_STEP) * QUANT_STEP
            q = x_quant + (latent - x_quant.detach()) * 0.5
            mu, scale, weight = entropy_model(q)
            nll = gmm_likelihood_discrete(q, mu, scale, weight, step=QUANT_STEP)
            bits = (nll.item() / np.log(2)) * q.numel()
            total_bits += bits
            recon = autoencoder.decode(q, target_size=(RESOLUTION, RESOLUTION))
            total_mse += torch.nn.functional.mse_loss(recon, x).item()
            total_pix += x.numel()
    return total_bits / total_pix, 10 * np.log10(1.0 / (total_mse / len(frames)))

print("Setup complete. Using exact repo classes.")

# ============================================================
# Quick BPP verification with the exact paper evaluation code
# ============================================================
ae_path = '/content/ae_lambda_0.05_final.pt'
ent_path = '/content/entropy_lambda_0.05_final.pt'

# Load test frames
import cv2
cap = cv2.VideoCapture('/content/walking_day_outdoor_1_1.mpg')
test_frames = []
while len(test_frames) < 100:
    ret, frame = cap.read()
    if not ret: break
    frame = cv2.resize(frame, (RESOLUTION, RESOLUTION))
    test_frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0)
cap.release()

bpp, psnr = evaluate_model(ae_path, ent_path, test_frames)
print(f"BPP: {bpp:.6f}")
print(f"PSNR: {psnr:.2f} dB")