# -*- coding: utf-8 -*-
"""probe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkQZUPZoIR0IeNGy4pGP6rKY0tj_dlik
"""

# ============================================================
# CELL 1: Setup — clone repo and import exact classes from milestone1
# ============================================================
!git clone https://github.com/thepreetam/le-maia.git /content/le-maia -q 2>/dev/null
!pip install -e /content/le-maia -q 2>/dev/null
!pip install opencv-python-headless ultralytics torch torchvision numpy matplotlib tqdm -q 2>/dev/null

import sys, torch, torch.nn as nn, numpy as np, cv2, os, subprocess, glob, shutil, random
from torch.distributions.normal import Normal
from tqdm import tqdm

sys.path.insert(0, '/content/le-maia/src')
from lewm_vc.encoder import LeWMEncoder

torch.manual_seed(42); np.random.seed(42); random.seed(42)
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
RESOLUTION = 256
QUANT_STEP = 2.0 / 255

# Import the EXACT classes from the repo's milestone1_rd_curve.py
# These match the checkpoint exactly — no redefinitions
class ResidualBlock(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.norm1 = nn.InstanceNorm2d(channels)
        self.conv1 = nn.Conv2d(channels, channels, 3, padding=1)
        self.norm2 = nn.InstanceNorm2d(channels)
        self.conv2 = nn.Conv2d(channels, channels, 3, padding=1)
    def forward(self, x):
        residual = x
        x = torch.nn.functional.gelu(self.norm1(x))
        x = self.conv1(x)
        x = torch.nn.functional.gelu(self.norm2(x))
        x = self.conv2(x)
        return x + residual

class LeWMDecoder(nn.Module):
    def __init__(self, latent_dim=192, hidden_dim=512):
        super().__init__()
        self.proj = nn.Conv2d(latent_dim, hidden_dim, 1)
        self.up1 = nn.ConvTranspose2d(hidden_dim, hidden_dim//2, 4, 2, 1)
        self.res1 = ResidualBlock(hidden_dim//2)
        self.up2 = nn.ConvTranspose2d(hidden_dim//2, hidden_dim//4, 4, 2, 1)
        self.res2 = ResidualBlock(hidden_dim//4)
        self.up3 = nn.ConvTranspose2d(hidden_dim//4, hidden_dim//8, 4, 2, 1)
        self.res3 = ResidualBlock(hidden_dim//8)
        self.up4 = nn.ConvTranspose2d(hidden_dim//8, hidden_dim//16, 4, 2, 1)
        self.res4 = ResidualBlock(hidden_dim//16)
        self.final = nn.Sequential(
            nn.Conv2d(hidden_dim//16, hidden_dim//32, 3, 1, 1),
            nn.InstanceNorm2d(hidden_dim//32),
            nn.GELU(),
            nn.Conv2d(hidden_dim//32, 3, 3, 1, 1),
        )
    def forward(self, latent, target_size=None):
        x = self.proj(latent)
        x = self.up1(x); x = self.res1(x)
        x = self.up2(x); x = self.res2(x)
        x = self.up3(x); x = self.res3(x)
        x = self.up4(x); x = self.res4(x)
        x = torch.sigmoid(self.final(x))
        if target_size:
            x = torch.nn.functional.interpolate(x, size=target_size, mode='bilinear', align_corners=False)
        return x

class AffineNormalization(nn.Module):
    def __init__(self, num_channels):
        super().__init__()
        self.scale = nn.Parameter(torch.ones(1, num_channels, 1, 1))
        self.shift = nn.Parameter(torch.zeros(1, num_channels, 1, 1))
    def forward(self, x):
        return x * self.scale + self.shift

class GMMEntropyModel(nn.Module):
    def __init__(self, latent_dim=192, hyper_channels=256, num_components=2):
        super().__init__()
        self.latent_dim = latent_dim
        self.num_components = num_components
        self.hyperprior = nn.Sequential(
            nn.Conv2d(latent_dim, hyper_channels, 3, padding=1), nn.ReLU(),
            nn.Conv2d(hyper_channels, hyper_channels, 3, padding=1, stride=2), nn.ReLU(),
            nn.Conv2d(hyper_channels, hyper_channels, 3, padding=1), nn.ReLU(),
            nn.ConvTranspose2d(hyper_channels, hyper_channels, 4, stride=2, padding=1), nn.ReLU(),
            nn.Conv2d(hyper_channels, latent_dim * num_components * 3, 3, padding=1),
        )
        self.softplus = nn.Softplus()

    def forward(self, x):
        params = self.hyperprior(x)
        B, C, H, W = params.shape
        channels_per_comp = C // self.num_components
        params = params.view(B, self.num_components, channels_per_comp, H, W)
        mu = params[:, :, :self.latent_dim, :, :]
        log_scale = params[:, :, self.latent_dim:2*self.latent_dim, :, :]
        log_weight = params[:, :, 2*self.latent_dim:3*self.latent_dim, :, :]
        scale = self.softplus(log_scale) + 1e-5
        weight = torch.softmax(log_weight, dim=1)
        return mu, scale, weight

class VideoAutoencoder(nn.Module):
    def __init__(self, latent_dim=192):
        super().__init__()
        self.encoder = LeWMEncoder(latent_dim=latent_dim, semantic_surprise=True)
        self.decoder = LeWMDecoder(latent_dim=latent_dim)
        self.affine = AffineNormalization(latent_dim)
    def encode(self, x):
        return self.affine(self.encoder(x, return_surprise=False))
    def decode(self, latent, target_size):
        return self.decoder(latent, target_size=target_size)

def gmm_likelihood_discrete(y, mu, scale, weight, step, epsilon=1e-12):
    B, C, H, W = y.shape
    num_comp = mu.shape[1]
    y_expanded = y.unsqueeze(1).expand(-1, num_comp, -1, -1, -1)
    normal = Normal(mu, scale)
    cdf_upper = normal.cdf(y_expanded + 0.5 * step)
    cdf_lower = normal.cdf(y_expanded - 0.5 * step)
    pmf = torch.clamp(cdf_upper - cdf_lower, min=epsilon, max=1.0)
    mixture_pmf = (weight * pmf).sum(dim=1)
    return -torch.log(mixture_pmf).mean()

def evaluate_model(ae_path, ent_path, frames):
    """Exact copy of milestone1_rd_curve.py evaluate_model()"""
    autoencoder = VideoAutoencoder().to(DEVICE)
    autoencoder.load_state_dict(torch.load(ae_path, map_location=DEVICE, weights_only=False), strict=False)
    autoencoder.eval()
    entropy_model = GMMEntropyModel().to(DEVICE)
    state = torch.load(ent_path, map_location=DEVICE, weights_only=False)
    for k in list(state.keys()):
        if 'mask' in k: del state[k]
    entropy_model.load_state_dict(state, strict=False)
    entropy_model.eval()
    total_bits, total_mse, total_pix = 0.0, 0.0, 0
    with torch.no_grad():
        for frame in frames:
            x = torch.from_numpy(frame).permute(2,0,1).unsqueeze(0).float().to(DEVICE)
            latent = autoencoder.encode(x)
            x_quant = torch.round(latent / QUANT_STEP) * QUANT_STEP
            q = x_quant + (latent - x_quant.detach()) * 0.5
            mu, scale, weight = entropy_model(q)
            nll = gmm_likelihood_discrete(q, mu, scale, weight, step=QUANT_STEP)
            bits = (nll.item() / np.log(2)) * q.numel()
            total_bits += bits
            recon = autoencoder.decode(q, target_size=(RESOLUTION, RESOLUTION))
            total_mse += torch.nn.functional.mse_loss(recon, x).item()
            total_pix += x.numel()
    return total_bits / total_pix, 10 * np.log10(1.0 / (total_mse / len(frames)))

print("Setup complete. Using exact repo classes.")

print('LeWMDecoder' in dir())
print('VideoAutoencoder' in dir())

# ============================================================
# CONSOLIDATED SETUP — run this once, then proceed to Cell 3
# ============================================================
!pip install -q opencv-python-headless ultralytics torch torchvision numpy matplotlib tqdm
import torch, torch.nn as nn, numpy as np, cv2, os, subprocess, glob, shutil, random, json
from torch.distributions.normal import Normal
from tqdm import tqdm

torch.manual_seed(42); np.random.seed(42); random.seed(42)
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
RESOLUTION = 256
QUANT_STEP = 2.0 / 255

class ResidualBlock(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.norm1 = nn.InstanceNorm2d(channels); self.conv1 = nn.Conv2d(channels, channels, 3, padding=1)
        self.norm2 = nn.InstanceNorm2d(channels); self.conv2 = nn.Conv2d(channels, channels, 3, padding=1)
    def forward(self, x):
        r = x; x = torch.nn.functional.gelu(self.norm1(x)); x = self.conv1(x)
        x = torch.nn.functional.gelu(self.norm2(x)); x = self.conv2(x); return x + r

class LeWMDecoder(nn.Module):
    def __init__(self, latent_dim=192, hidden_dim=512):
        super().__init__()
        self.proj = nn.Conv2d(latent_dim, hidden_dim, 1)
        self.up1 = nn.ConvTranspose2d(hidden_dim, hidden_dim//2, 4,2,1); self.res1 = ResidualBlock(hidden_dim//2)
        self.up2 = nn.ConvTranspose2d(hidden_dim//2, hidden_dim//4, 4,2,1); self.res2 = ResidualBlock(hidden_dim//4)
        self.up3 = nn.ConvTranspose2d(hidden_dim//4, hidden_dim//8, 4,2,1); self.res3 = ResidualBlock(hidden_dim//8)
        self.up4 = nn.ConvTranspose2d(hidden_dim//8, hidden_dim//16, 4,2,1); self.res4 = ResidualBlock(hidden_dim//16)
        self.final = nn.Sequential(
            nn.Conv2d(hidden_dim//16, hidden_dim//32, 3,1,1), nn.InstanceNorm2d(hidden_dim//32),
            nn.GELU(), nn.Conv2d(hidden_dim//32, 3,3,1,1),
        )
    def forward(self, latent, target_size=None):
        x = self.proj(latent); x = self.up1(x); x = self.res1(x); x = self.up2(x); x = self.res2(x)
        x = self.up3(x); x = self.res3(x); x = self.up4(x); x = self.res4(x)
        x = torch.sigmoid(self.final(x))
        if target_size: x = torch.nn.functional.interpolate(x, size=target_size, mode='bilinear', align_corners=False)
        return x

class AffineNormalization(nn.Module):
    def __init__(self, n): super().__init__(); self.scale = nn.Parameter(torch.ones(1, n, 1, 1)); self.shift = nn.Parameter(torch.zeros(1, n, 1, 1))
    def forward(self, x): return x * self.scale + self.shift

class GMMEntropyModel(nn.Module):
    def __init__(self, latent_dim=192, hyper_channels=256, num_components=2):
        super().__init__(); self.latent_dim = latent_dim; self.num_components = num_components
        self.hyperprior = nn.Sequential(
            nn.Conv2d(latent_dim, hyper_channels, 3, padding=1), nn.ReLU(),
            nn.Conv2d(hyper_channels, hyper_channels, 3, padding=1, stride=2), nn.ReLU(),
            nn.Conv2d(hyper_channels, hyper_channels, 3, padding=1), nn.ReLU(),
            nn.ConvTranspose2d(hyper_channels, hyper_channels, 4, stride=2, padding=1), nn.ReLU(),
            nn.Conv2d(hyper_channels, latent_dim * num_components * 3, 3, padding=1),
        ); self.softplus = nn.Softplus()
    def forward(self, x):
        params = self.hyperprior(x); B, C, H, W = params.shape; cp = C // self.num_components
        params = params.view(B, self.num_components, cp, H, W)
        mu = params[:, :, :self.latent_dim, :, :]; log_scale = params[:, :, self.latent_dim:2*self.latent_dim, :, :]
        log_weight = params[:, :, 2*self.latent_dim:3*self.latent_dim, :, :]
        scale = self.softplus(log_scale) + 1e-5; weight = torch.softmax(log_weight, dim=1)
        return mu, scale, weight

def gmm_likelihood_discrete(y, mu, scale, weight, step, eps=1e-12):
    B, C, H, W = y.shape; nc = mu.shape[1]; ye = y.unsqueeze(1).expand(-1, nc, -1, -1, -1)
    n = Normal(mu, scale); pmf = torch.clamp(n.cdf(ye + 0.5*step) - n.cdf(ye - 0.5*step), min=eps, max=1.0)
    return -torch.log((weight * pmf).sum(dim=1)).mean()

class PatchEmbed(nn.Module):
    def __init__(self, img_size=256, patch_size=16, in_chans=3, embed_dim=192):
        super().__init__(); self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size)
    def forward(self, x): return self.proj(x)

class TransformerEncoderLayer(nn.Module):
    def __init__(self, d_model, nhead, dim_feedforward=2048, dropout=0.1):
        super().__init__()
        self.self_attn = nn.MultiheadAttention(d_model, nhead, dropout=dropout, batch_first=True)
        self.linear1 = nn.Linear(d_model, dim_feedforward); self.dropout = nn.Dropout(dropout)
        self.linear2 = nn.Linear(dim_feedforward, d_model)
        self.norm1 = nn.LayerNorm(d_model); self.norm2 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout); self.dropout2 = nn.Dropout(dropout)
        self.activation = nn.GELU()
    def forward(self, src):
        src2 = self.norm1(src); src2 = self.self_attn(src2, src2, src2)[0]; src = src + self.dropout1(src2)
        src2 = self.norm2(src); src = src + self.dropout2(self.linear2(self.dropout(self.activation(self.linear1(src2)))))
        return src

class LeWMEncoder(nn.Module):
    def __init__(self, latent_dim=192, patch_size=16, hidden_dim=192, num_layers=6, num_heads=3, mlp_ratio=4.0):
        super().__init__()
        self.patch_embed = PatchEmbed(embed_dim=hidden_dim)
        self.cls_token = nn.Parameter(torch.zeros(1, 1, hidden_dim))
        self.pos_embed = nn.Parameter(torch.zeros(1, 1, hidden_dim))
        self.encoder_layers = nn.ModuleList([
            TransformerEncoderLayer(hidden_dim, num_heads, int(hidden_dim * mlp_ratio))
            for _ in range(num_layers)
        ])
        self.norm = nn.LayerNorm(hidden_dim)
        self.latent_proj = nn.Conv2d(hidden_dim, latent_dim, kernel_size=1)
    def forward(self, x, return_surprise=False):
        B, C, H, W = x.shape
        x = self.patch_embed(x); x = x.flatten(2).permute(0, 2, 1)
        cls_tokens = self.cls_token.expand(B, -1, -1); x = torch.cat([cls_tokens, x], dim=1)
        x = x + self.pos_embed
        for layer in self.encoder_layers: x = layer(x)
        x = self.norm(x); x = x[:, 1:, :]
        h, w = H // 16, W // 16; x = x.permute(0, 2, 1).reshape(B, -1, h, w)
        return self.latent_proj(x)

class VideoAutoencoder(nn.Module):
    def __init__(self, latent_dim=192):
        super().__init__()
        self.encoder = LeWMEncoder(latent_dim=latent_dim)
        self.decoder = LeWMDecoder(latent_dim=latent_dim)
        self.affine = AffineNormalization(latent_dim)
    def encode(self, x): return self.affine(self.encoder(x))
    def decode(self, latent, target_size): return self.decoder(latent, target_size=target_size)

print("Setup complete. All classes defined.")

# ============================================================
# CELL 2: Upload Milestone 1 checkpoint and PEViD-HD video
# ============================================================
ae_path = '/content/ae_lambda_0.05_final.pt'
ent_path = '/content/entropy_lambda_0.05_final.pt'

print("Upload ae_lambda_0.05_final.pt and entropy_lambda_0.05_final.pt:")
uploaded_ckpt = files.upload()
ae_path = '/content/ae_lambda_0.05_final.pt'
ent_path = '/content/entropy_lambda_0.05_final.pt'
for f in uploaded_ckpt.keys():
    if 'ae_lambda' in f: ae_path = f'/content/{f}'
    elif 'entropy_lambda' in f: ent_path = f'/content/{f}'

print("\nUpload PEViD-HD walking video (walking_day_outdoor_1_1.mpg):")
uploaded_video = files.upload()
video_path = '/content/walking_day_outdoor_1_1.mpg'
for f in uploaded_video.keys():
    if f.endswith(('.mpg', '.mp4', '.avi')):
        video_path = f'/content/{f}'
        break

print(f"\nAE checkpoint: {ae_path} ({os.path.getsize(ae_path)/1e6:.1f} MB)")
print(f"Entropy checkpoint: {ent_path} ({os.path.getsize(ent_path)/1e6:.1f} MB)")
print(f"Video: {video_path}")

# ============================================================
# CELL 3: Extract LeWM-VC latents at λ=0.05 (target BPP ~0.109)
# ============================================================
# Load autoencoder and entropy model
ae_path = '/content/ae_lambda_0.05_final.pt'
ent_path = '/content/entropy_lambda_0.05_final.pt'

autoencoder = VideoAutoencoder(latent_dim=192).to(DEVICE)
autoencoder.load_state_dict(torch.load(ae_path, map_location=DEVICE, weights_only=False), strict=False)
autoencoder.eval()

entropy_model = GMMEntropyModel(latent_dim=192).to(DEVICE)
state = torch.load(ent_path, map_location=DEVICE, weights_only=False)
for k in list(state.keys()):
    if 'mask' in k: del state[k]
entropy_model.load_state_dict(state, strict=False)
entropy_model.eval()

# Read video frames (use same frames as original probe experiment: 200 train, 50 test)
cap = cv2.VideoCapture(video_path)
all_frames = []
while True:
    ret, frame = cap.read()
    if not ret: break
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    frame_rgb = cv2.resize(frame_rgb, (RESOLUTION, RESOLUTION))
    all_frames.append(frame_rgb)
cap.release()
print(f"Total frames extracted: {len(all_frames)}")

# Use first 200 for training, next 50 for test
train_frames = all_frames[:200]
test_frames = all_frames[200:250]
print(f"Train: {len(train_frames)}, Test: {len(test_frames)}")

# Extract latents for both sets
def extract_latent(frame_rgb):
    x = torch.from_numpy(frame_rgb.astype(np.float32)/255.0).permute(2,0,1).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        latent = autoencoder.encode(x)
        xq = torch.round(latent / QUANT_STEP) * QUANT_STEP
        q = xq + (latent - xq.detach()) * 0.5  # STE, same as training
    return q.squeeze(0).cpu()

print("Extracting training latents...")
train_latents = torch.stack([extract_latent(f) for f in tqdm(train_frames)])
print("Extracting test latents...")
test_latents = torch.stack([extract_latent(f) for f in tqdm(test_frames)])

# Compute actual BPP on test set
total_bits = 0
for latent in test_latents:
    latent = latent.unsqueeze(0).to(DEVICE)
    mu, scale, weight = entropy_model(latent)
    nll = gmm_likelihood_discrete(latent, mu, scale, weight, step=QUANT_STEP)
    bits = (nll.item() / np.log(2)) * latent.numel()
    total_bits += bits
lewm_bpp = total_bits / (len(test_latents) * RESOLUTION * RESOLUTION * 3)
print(f"\nLeWM-VC intra-frame BPP (λ=0.05): {lewm_bpp:.4f}")
assert 0.10 <= lewm_bpp <= 0.13, f"BPP out of expected range: {lewm_bpp}"
print("BPP verified – operational bitrate confirmed.")

# Exact replication of milestone1 evaluate_model() BPP calculation
import torch
from torch.distributions.normal import Normal

def evaluate_model_bpp(ae_ckpt_path, ent_ckpt_path, frames):
    autoencoder = VideoAutoencoder(latent_dim=192).to(DEVICE)
    autoencoder.load_state_dict(torch.load(ae_ckpt_path, map_location=DEVICE, weights_only=False), strict=False)
    autoencoder.eval()
    entropy_model = GMMEntropyModel(latent_dim=192).to(DEVICE)
    state = torch.load(ent_ckpt_path, map_location=DEVICE, weights_only=False)
    for k in list(state.keys()):
        if 'mask' in k: del state[k]
    entropy_model.load_state_dict(state, strict=False)
    entropy_model.eval()

    total_bits = 0.0
    total_pix = 0
    with torch.no_grad():
        for frame in frames:
            x = torch.from_numpy(frame.astype(np.float32)/255.0).permute(2,0,1).unsqueeze(0).to(DEVICE)
            latent = autoencoder.encode(x)
            q = torch.round(latent / QUANT_STEP) * QUANT_STEP  # hard rounding, exactly as paper
            mu, scale, weight = entropy_model(q)

            # Paper's exact NLL computation
            nc = mu.shape[1]
            ye = q.unsqueeze(1).expand(-1, nc, -1, -1, -1)
            n = Normal(mu, scale)
            pmf = torch.clamp(n.cdf(ye + 0.5*QUANT_STEP) - n.cdf(ye - 0.5*QUANT_STEP), min=1e-12, max=1.0)
            mixture_pmf = (weight * pmf).sum(dim=1)
            nll = -torch.log(mixture_pmf).mean()
            bits = (nll.item() / np.log(2)) * q.numel()
            total_bits += bits
            total_pix += x.numel()
    return total_bits / total_pix

bpp = evaluate_model_bpp(ae_path, ent_path, test_frames[:10])
print(f"BPP (paper evaluation method, 10 frames): {bpp:.4f}")

import glob, os

ae_files = sorted(glob.glob('/content/ae_lambda_*_final.pt'))
ent_files = sorted(glob.glob('/content/entropy_lambda_*_final.pt'))

for ae_f, ent_f in zip(ae_files, ent_files):
    lam = ae_f.split('_lambda_')[1].split('_final')[0]
    bpp = evaluate_model_bpp(ae_f, ent_f, test_frames[:10])
    print(f"λ={lam}: BPP={bpp:.4f}")

import torch
from torch.distributions.normal import Normal

# Load one latent and inspect
latent = test_latents[0].unsqueeze(0).to(DEVICE)
print(f"Latent shape: {latent.shape}")
print(f"Latent min/max/mean/std: {latent.min().item():.4f} / {latent.max().item():.4f} / {latent.mean().item():.4f} / {latent.std().item():.4f}")

# Forward pass through entropy model
entropy_model.eval()
with torch.no_grad():
    mu, scale, weight = entropy_model(latent)
    print(f"\nMu shape: {mu.shape}, Scale shape: {scale.shape}, Weight shape: {weight.shape}")
    print(f"Mu range: [{mu.min().item():.4f}, {mu.max().item():.4f}]")
    print(f"Scale range: [{scale.min().item():.6f}, {scale.max().item():.4f}]")
    print(f"Weight range: [{weight.min().item():.4f}, {weight.max().item():.4f}]")

    # Compute NLL manually step by step
    ye = latent.unsqueeze(1).expand(-1, 2, -1, -1, -1)
    n = Normal(mu, scale)
    cdf_upper = n.cdf(ye + 0.5 * QUANT_STEP)
    cdf_lower = n.cdf(ye - 0.5 * QUANT_STEP)
    pmf = torch.clamp(cdf_upper - cdf_lower, min=1e-12, max=1.0)
    mixture_pmf = (weight * pmf).sum(dim=1)
    nll = -torch.log(mixture_pmf)
    print(f"\nPMF min/mean/max: {pmf.min().item():.6f} / {pmf.mean().item():.6f} / {pmf.max().item():.6f}")
    print(f"Mixture PMF min/mean/max: {mixture_pmf.min().item():.6f} / {mixture_pmf.mean().item():.6f} / {mixture_pmf.max().item():.6f}")
    print(f"NLL per element mean: {nll.mean().item():.4f} nats")

    # Total bits
    bits = (nll.mean().item() / np.log(2)) * latent.numel()
    bpp = bits / (256 * 256 * 3)
    print(f"\nBits: {bits:.0f}, BPP: {bpp:.4f}")

import torch
ckpt = torch.load('/content/ae_lambda_0.05_final.pt', map_location='cpu', weights_only=False)
print("Top-level keys:", list(ckpt.keys()))
# Check if this is a training state or inference state
for k, v in ckpt.items():
    print(f"  {k}: type={type(v).__name__}", end="")
    if hasattr(v, 'shape'):
        print(f", shape={v.shape}")
    else:
        print()

ent_ckpt = torch.load('/content/entropy_lambda_0.05_final.pt', map_location='cpu', weights_only=False)
print("Entropy checkpoint keys:", list(ent_ckpt.keys()))

# ============================================================
# CELL 4: Generate x265 frames at matched BPP (~0.11)
# ============================================================
# Encode the 250 frames as PNGs for x265
!mkdir -p /content/x265_frames
train_test_frames = train_frames + test_frames
for i, f in enumerate(train_test_frames):
    cv2.imwrite(f'/content/x265_frames/frame_{i:06d}.png', cv2.cvtColor(f, cv2.COLOR_RGB2BGR))

# Binary search for CRF matching LeWM BPP
target_bpp = lewm_bpp
lo, hi = 0, 51
best_crf, best_bpp = 23, float('inf')
best_out = None

print(f"Searching x265 CRF to match {target_bpp:.4f} BPP...")
for _ in range(10):
    mid = int((lo + hi) / 2)
    out_path = f'/content/x265_crf{mid}.mp4'
    cmd = ['ffmpeg', '-y', '-framerate', '25',
           '-i', '/content/x265_frames/frame_%06d.png',
           '-c:v', 'libx265', '-crf', str(mid), '-preset', 'medium',
           '-x265-params', 'log-level=error', out_path]
    result = subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if result.returncode != 0:
        hi = mid
        continue
    file_bits = os.path.getsize(out_path) * 8
    bpp = file_bits / (len(train_test_frames) * RESOLUTION * RESOLUTION * 3)
    print(f"  CRF={mid:2d}: BPP={bpp:.4f}")
    if abs(bpp - target_bpp) < abs(best_bpp - target_bpp):
        best_crf, best_bpp = mid, bpp
        if best_out: os.remove(best_out)
        best_out = out_path
    else:
        os.remove(out_path)
    if bpp > target_bpp: lo = mid
    else: hi = mid
    if lo >= hi - 1: break

print(f"\nBest CRF={best_crf}: BPP={best_bpp:.4f} (target {target_bpp:.4f})")

# Decode back to PNGs
!mkdir -p /content/x265_decoded
subprocess.run(['ffmpeg', '-y', '-i', best_out, '/content/x265_decoded/frame_%06d.png'],
               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)

# Load decoded frames (250 frames)
x265_frames = []
for p in sorted(glob.glob('/content/x265_decoded/frame_*.png')):
    img = cv2.imread(p)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    x265_frames.append(img)
print(f"Loaded {len(x265_frames)} x265-decoded frames.")

# Split into train/test
x265_train = x265_frames[:200]
x265_test = x265_frames[200:250]

# ============================================================
# CELL 5: Generate YOLOv5s teacher labels on uncompressed frames
# ============================================================
from ultralytics import YOLO
model_yolo = YOLO('yolov5su.pt')  # Use ultralytics YOLO for simplicity
model_yolo.to(DEVICE)

def generate_targets(frame_bgr):
    """Run YOLOv5s, return objectness map [16,16] and class map [16,16]"""
    results = model_yolo(frame_bgr, verbose=False)[0]
    obj_t = torch.zeros(16, 16)
    cls_t = torch.full((16, 16), -1, dtype=torch.long)
    if results.boxes is not None and len(results.boxes) > 0:
        boxes = results.boxes.xyxy.cpu().numpy()
        clss = results.boxes.cls.cpu().numpy().astype(int)
        for (x1, y1, x2, y2), cls_id in zip(boxes, clss):
            cx = (x1 + x2) / 2 / RESOLUTION
            cy = (y1 + y2) / 2 / RESOLUTION
            gx = min(int(cx * 16), 15)
            gy = min(int(cy * 16), 15)
            obj_t[gy, gx] = 1.0
            cls_t[gy, gx] = cls_id
    return obj_t, cls_t

print("Generating teacher targets for training frames...")
train_targets = [generate_targets(f) for f in tqdm(train_frames, desc="Train targets")]
print("Generating teacher targets for test frames...")
test_targets = [generate_targets(f) for f in tqdm(test_frames, desc="Test targets")]

# Stack targets
train_obj = torch.stack([t[0] for t in train_targets])
train_cls = torch.stack([t[1] for t in train_targets])
test_obj = torch.stack([t[0] for t in test_targets])
test_cls = torch.stack([t[1] for t in test_targets])

# ============================================================
# CELL 6: Define Probes, Train, and Evaluate
# ============================================================
# Latent Probe (same as Section 4.4)
class LatentProbe(nn.Module):
    def __init__(self, latent_dim=192, num_classes=80):
        super().__init__()
        self.conv1 = nn.Conv2d(latent_dim, 128, 3, padding=1)
        self.conv2 = nn.Conv2d(128, 64, 3, padding=1)
        self.conv3 = nn.Conv2d(64, 32, 3, padding=1)
        self.obj_head = nn.Conv2d(32, 1, 1)
        self.cls_head = nn.Conv2d(32, num_classes, 1)
        self.act = nn.GELU()
    def forward(self, latent):
        x = self.act(self.conv1(latent))
        x = self.act(self.conv2(x))
        x = self.act(self.conv3(x))
        return self.obj_head(x), self.cls_head(x)

# Pixel Probe (same architecture, 3-channel RGB input)
class PixelProbe(nn.Module):
    def __init__(self, num_classes=80):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1, stride=2)    # 128
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1, stride=2)   # 64
        self.conv3 = nn.Conv2d(64, 128, 3, padding=1, stride=2)  # 32
        self.conv4 = nn.Conv2d(128, 128, 3, padding=1, stride=2) # 16
        self.obj_head = nn.Conv2d(128, 1, 1)
        self.cls_head = nn.Conv2d(128, num_classes, 1)
        self.act = nn.GELU()
    def forward(self, img):
        x = self.act(self.conv1(img))
        x = self.act(self.conv2(x))
        x = self.act(self.conv3(x))
        x = self.act(self.conv4(x))
        return self.obj_head(x), self.cls_head(x)

# Training function
def train_probe(probe, train_inputs, train_obj_targets, train_cls_targets, epochs=50, lr=1e-3):
    probe.to(DEVICE)
    opt = torch.optim.AdamW(probe.parameters(), lr=lr)
    obj_loss_fn = nn.BCEWithLogitsLoss()
    cls_loss_fn = nn.CrossEntropyLoss(ignore_index=-1)
    dataset = torch.utils.data.TensorDataset(train_inputs, train_obj_targets, train_cls_targets)
    loader = torch.utils.data.DataLoader(dataset, batch_size=8, shuffle=True)
    for epoch in range(epochs):
        probe.train()
        total_loss = 0
        for batch_inputs, batch_obj, batch_cls in loader:
            batch_inputs = batch_inputs.to(DEVICE)
            batch_obj = batch_obj.to(DEVICE)
            batch_cls = batch_cls.to(DEVICE)
            obj_pred, cls_pred = probe(batch_inputs)
            loss_obj = obj_loss_fn(obj_pred.squeeze(1), batch_obj)
            loss_cls = cls_loss_fn(cls_pred.permute(0,2,3,1).reshape(-1, 80), batch_cls.reshape(-1))
            loss = loss_obj + loss_cls
            opt.zero_grad()
            loss.backward()
            opt.step()
            total_loss += loss.item()
        if (epoch+1) % 10 == 0:
            print(f"  Epoch {epoch+1}/{epochs}, loss: {total_loss/len(loader):.4f}")

# Evaluation function
def evaluate_probe(probe, inputs, obj_targets, cls_targets):
    probe.eval()
    obj_correct = 0
    cls_correct = 0
    total_obj = 0
    total_cls = 0
    with torch.no_grad():
        for i in range(len(inputs)):
            inp = inputs[i].unsqueeze(0).to(DEVICE)
            obj_pred, cls_pred = probe(inp)
            obj_pred_bin = (torch.sigmoid(obj_pred.squeeze()) > 0.5).float()
            obj_correct += (obj_pred_bin == obj_targets[i].to(DEVICE)).sum().item()
            total_obj += obj_targets[i].numel()
            mask = obj_targets[i] == 1.0
            if mask.sum() > 0:
                cls_pred_labels = cls_pred.squeeze(0).permute(1,2,0)[mask].argmax(dim=-1)
                cls_correct += (cls_pred_labels == cls_targets[i][mask].to(DEVICE)).sum().item()
                total_cls += mask.sum().item()
    return obj_correct/total_obj, cls_correct/total_cls if total_cls > 0 else 0.0

# --- Train Latent Probe ---
print("\n=== Training Latent Probe ===")
latent_probe = LatentProbe()
train_probe(latent_probe, train_latents, train_obj, train_cls)
obj_acc_lat, cls_acc_lat = evaluate_probe(latent_probe, test_latents, test_obj, test_cls)
print(f"Latent Probe Results: Obj Acc={obj_acc_lat:.4f}, Class Acc={cls_acc_lat:.4f}")

# --- Train Pixel Probe ---
print("\n=== Training Pixel Probe ===")
x265_train_tensors = torch.stack([torch.from_numpy(f.astype(np.float32)/255.0).permute(2,0,1) for f in x265_train])
pixel_probe = PixelProbe()
train_probe(pixel_probe, x265_train_tensors, train_obj, train_cls)
x265_test_tensors = torch.stack([torch.from_numpy(f.astype(np.float32)/255.0).permute(2,0,1) for f in x265_test])
obj_acc_pix, cls_acc_pix = evaluate_probe(pixel_probe, x265_test_tensors, test_obj, test_cls)
print(f"Pixel Probe Results: Obj Acc={obj_acc_pix:.4f}, Class Acc={cls_acc_pix:.4f}")

# --- Final Comparison ---
print("\n" + "="*60)
print(f"FINAL RESULTS at Operational Bitrate (~{lewm_bpp:.4f} BPP)")
print("="*60)
print(f"Latent Probe (LeWM-VC): Class Acc = {cls_acc_lat:.4f}")
print(f"Pixel Probe (x265):     Class Acc = {cls_acc_pix:.4f}")
print(f"Difference: {cls_acc_lat - cls_acc_pix:+.4f}")
if cls_acc_lat >= 0.82:
    print("✅ VERDICT: Claim VALIDATED. 13.7x storage + high accuracy confirmed.")
elif cls_acc_lat >= 0.75:
    print("⚠️ VERDICT: Claim PARTIALLY validated. Latent still wins but margin shrinks.")
elif cls_acc_lat >= 0.65:
    print("⚠️ VERDICT: Claim WEAKENS. Consider separating storage and accuracy claims.")
else:
    print("❌ VERDICT: Claim BROKEN. Do not pair storage savings with accuracy.")

